<?php

/**
 * @file
 * Contains xinh_vnn_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function xinh_vnn_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the xinh_vnn_content module.
    case 'help.page.xinh_vnn_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function xinh_vnn_content_theme() {
  return [
    'xinh_vnn_content' => [
      'template' => 'xinh_vnn_content',
      'render element' => 'children',
    ],
  ];
}
